version: "3"
services:
  nginx:
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=sibi
      - MONGO_PASSWORD=Hindustan1
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sibi
      - MONGO_INITDB_ROOT_PASSWORD=Hindustan1
  
        


    